version: "2"

services:
  elasticsearch:
    image: elasticsearch:5.2.2-alpine
    restart: always
    hostname: fpc-elasticsearch
    container_name: fpc-elasticsearch
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/moloch/elasticsearch:/usr/share/elasticsearch/data
    network_mode: bridge

  capture:
    build: ./fpc-moloch
    image: xme/fpc-moloch:latest
    restart: always
    hostname: fpc-moloch
    container_name: fpc-moloch
    depends_on:
      - fpc-elasticsearch
    links:
      - fpc-elasticsearch:elasticsearch
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/moloch/core/etc:/data/moloch/etc:rw
      - /data/moloch/core/raw:/data/moloch/raw:rw
      - /data/pcap:/data/pcap:rw
    ports:
      - '8443:8443'
      - '8005:8005'
    network_mode: bridge
